### ISSUE TITLE
Invalid method name: 'executeAndWait' (Thrift::ApplicationException)

### ISSUE THREAD

**Issue by ejstembler** [colinmarc/impala-ruby#21]
I'm trying to test connecting via kerberos, however, I'm receiving this error:

<pre>
C:/Ruby21/lib/ruby/gems/2.1.0/gems/thrift-0.9.3.0/lib/thrift/client.rb:67:in `handle_exception': Invalid method name: 'executeAndWait' (Thrift::ApplicationException)

from C:/Ruby21/lib/ruby/gems/2.1.0/gems/thrift-0.9.3.0/lib/thrift/client.rb:55:in 'receive_message'
from C:/Ruby21/lib/ruby/gems/2.1.0/gems/impala-0.5.0/lib/impala/protocol/beeswax_service.rb:43:in 'recv_executeAndWait'
from C:/Ruby21/lib/ruby/gems/2.1.0/gems/impala-0.5.0/lib/impala/protocol/beeswax_service.rb:35:in 'executeAndWait'
from C:/Ruby21/lib/ruby/gems/2.1.0/gems/impala-0.5.0/lib/impala/connection.rb:107:in 'send_query'
from C:/Ruby21/lib/ruby/gems/2.1.0/gems/impala-0.5.0/lib/impala/connection.rb:82:in 'execute'
from C:/Ruby21/lib/ruby/gems/2.1.0/gems/impala-0.5.0/lib/impala/connection.rb:69:in 'query'
from C:/Users/ejstembler/RubymineProjects/ribu_impala_test/main.rb:6:in 'block in <top (required)>'
from C:/Ruby21/lib/ruby/gems/2.1.0/gems/impala-0.5.0/lib/impala.rb:49:in 'connect'
from C:/Users/ejstembler/RubymineProjects/ribu_impala_test/main.rb:5:in '<top (required)>'
from -e:1:in 'load'
from -e:1:in '<main>'
</pre>

**Comment by ejstembler** [comment]
Never mind, I saw the [comment](https://github.com/colinmarc/impala-ruby/issues/19#issuecomment-222096492) about using port <tt>21000</tt>.  Got it to work!
