### ISSUE TITLE
`rescue in read': end of file reached (Thrift::TransportException)

### ISSUE THREAD

**Issue by paulocheque** [colinmarc/impala-ruby#24]
- OSX 10.12.3
- Ruby 2.0.0
- gem install thrift -- --with-cppflags=\"-D_FORTIFY_SOURCE=0 -Wno-shift-negative-value\"
- gem install impala

Hi there, any ideas? I am receiving this error when I want to execute a query. Am I missing anything? Maybe some authentication issue, network issue?

Thanks in advance. 

```
require 'rubygems'
require 'impala'

Impala.connect('my ip', 21000) do |conn|
    puts conn
    puts conn.open?
    puts conn.inspect
    cursor = conn.query('my query') # ERROR in this line
    cursor.each do |row|
      puts row
    end
end

```

```
/Library/Ruby/Gems/2.0.0/gems/thrift-0.10.0.0/lib/thrift/transport/socket.rb:124:in `rescue in read': end of file reached (Thrift::TransportException)
	from /Library/Ruby/Gems/2.0.0/gems/thrift-0.10.0.0/lib/thrift/transport/socket.rb:99:in `read'
	from /Library/Ruby/Gems/2.0.0/gems/thrift-0.10.0.0/lib/thrift/transport/buffered_transport.rb:82:in `read_into_buffer'
	from /Library/Ruby/Gems/2.0.0/gems/thrift-0.10.0.0/lib/thrift/protocol/binary_protocol.rb:194:in `read_i32'
	from /Library/Ruby/Gems/2.0.0/gems/thrift-0.10.0.0/lib/thrift/protocol/binary_protocol.rb:120:in `read_message_begin'
	from /Library/Ruby/Gems/2.0.0/gems/thrift-0.10.0.0/lib/thrift/client.rb:54:in `receive_message'
	from /Library/Ruby/Gems/2.0.0/gems/impala-0.5.1/lib/impala/protocol/beeswax_service.rb:43:in `recv_executeAndWait'
	from /Library/Ruby/Gems/2.0.0/gems/impala-0.5.1/lib/impala/protocol/beeswax_service.rb:35:in `executeAndWait'
	from /Library/Ruby/Gems/2.0.0/gems/impala-0.5.1/lib/impala/connection.rb:97:in `send_query'
	from /Library/Ruby/Gems/2.0.0/gems/impala-0.5.1/lib/impala/connection.rb:81:in `execute'
	from /Library/Ruby/Gems/2.0.0/gems/impala-0.5.1/lib/impala/connection.rb:69:in `query'
	from a.rb:8:in `block in <main>'
	from /Library/Ruby/Gems/2.0.0/gems/impala-0.5.1/lib/impala.rb:49:in `connect'
	from a.rb:4:in `<main>'
```

**Comment by avinashrahul** [comment]
Hi Paulo,

Were you able to figure out this problem?

I am getting similar kind of error - What does **end of file reached** means?


```
Exception
Thrift::TransportException

Error
end of file reached

/apps/rvm/gems/ruby-2.4.2/gems/thrift-0.10.0.0/lib/thrift/transport/socket.rb:124:in `rescue in read'
/apps/rvm/gems/ruby-2.4.2/gems/thrift-0.10.0.0/lib/thrift/transport/socket.rb:99:in `read'
/apps/rvm/gems/ruby-2.4.2/gems/impala-1.0.RN/lib/impala/sasl_transport.rb:97:in `read_handshake_message'
/apps/rvm/gems/ruby-2.4.2/gems/impala-1.0.RN/lib/impala/sasl_transport.rb:50:in `handshake_plain!'
/apps/rvm/gems/ruby-2.4.2/gems/impala-1.0.RN/lib/impala/sasl_transport.rb:34:in `open' 
```

**Comment by paulocheque** [comment]
Sorry, I weren't able fix that and I am not working on that anymore.

**Comment by avinashrahul** [comment]
Ok cool, thanks!
